### ISSUE TITLE
"SyntaxError: duplicate argument" error found when using Python client API

### ISSUE THREAD

**Issue by wirawan0** [kaltura/KalturaGeneratedAPIClientsPython#8]
Hi,

I found error when running this initial code on Python:

```
from KalturaClient import *

config = KalturaConfiguration()
client = KalturaClient(config)
```

This is from the first code snippet in https://developer.kaltura.com/api-docs/VPaaS-API-Getting-Started/Getting-Started-VPaaS-API.html . The detailed error dump was:

```
Traceback (most recent call last):

  File "/Users/wpurwant/Applications/anaconda3-2020.11/envs/kaltura-test/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-1ce55f951fc6>", line 4, in <module>
    client = KalturaClient(config)

  File "/Users/wpurwant/Applications/anaconda3-2020.11/envs/kaltura-test/lib/python3.8/site-packages/KalturaClient/Client.py", line 132, in __init__
    self.loadPlugins()

  File "/Users/wpurwant/Applications/anaconda3-2020.11/envs/kaltura-test/lib/python3.8/site-packages/KalturaClient/Client.py", line 165, in loadPlugins
    self.loadPlugin(pluginFile)

  File "/Users/wpurwant/Applications/anaconda3-2020.11/envs/kaltura-test/lib/python3.8/site-packages/KalturaClient/Client.py", line 169, in loadPlugin
    pluginModule = __import__('.'.join(moduleHierarchy))

  File "/Users/wpurwant/Applications/anaconda3-2020.11/envs/kaltura-test/lib/python3.8/site-packages/KalturaClient/Plugins/Reach.py", line 2536
    def __init__(self,
    ^
SyntaxError: duplicate argument 'expectedFinishTimeGreaterThanOrEqual' in function definition
```

This was run under Python 3.8.5, with Anaconda python distribution, in a Mac system. But the error in line 2536 above seems to be consistent--my friend also encountered the same.

**Comment by kaltura-hooks** [comment]
Hi @wirawan0,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by wirawan0** [comment]
Opps ... wrong place to report issue. I noted another person already reported this issue on https://github.com/kaltura/clients-generator/issues/653 . Closing this one.
